### ISSUE TITLE
[BUG] Release 0.3.1 broke the table reference urls from the Journal

### ISSUE THREAD

**Issue by adunis** [p4535992/foundryvtt-creature-loot-crafting-and-gathering#1]
I'm not sure why it happened, but I noticed that you renamed the module folder from ' creature-loot'  to 'creature-loot-crafting-and-gathering'  and the journal its still pointing to the tables as if they were still part of the 'creature-loot'  compendium

**Comment by p4535992** [comment]
Fixed the issue on 0.3.2, but be careful I haven't had time to get jay's work back in hand, so the compendium isn't finished
